apps/order/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('channels/', views.channel_list),
    path('orders/', views.order_list),
    path('order/<int:pk>/', views.order_detail),
    path('order/<int:pk>/update/', views.order_update),
    path('order/<int:pk>/end/', views.end_order),
    path('order/<int:pk>/reject/', views.reject_order),
    path('order/<int:order_pk>/pass_to/', views.pass_order),

    path('order_pool/', views.order_pool_list),
    path('order_pool/<int:pk>/take/', views.order_pool_take),
    path('create/', views.order_create),
    path('import_channel/', views.import_channel),
    path('channel/<int:pk>/', views.channel_detail),
    path('channel/<int:pk>/update/', views.channel_update),
    path('report/', views.report),
]

odman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve

from odman import settings
from apps.order.views import my_login, my_logout, register, profile, profile_update, profile_confirm,\
    reset_passwd, apply_verify_code, order_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', order_list),
    path('accounts/login/', my_login),
    path('logout/', my_logout),
    path('accounts/register/', register),
    path('accounts/reset_passwd/', reset_passwd),
    path('accounts/apply_for_code/', apply_verify_code),
    path('profile/<int:pk>/', profile),
    path('profile/<int:pk>/confirm/', profile_confirm),
    path('profile/<int:pk>/update', profile_update),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('order/', include('apps.order.urls')),
]

apps/order/models.py
from hashlib import sha1
import random

from django.db import models
from django.contrib.auth.models import User

from odman import settings
from lib.models import BaseModel


class Channel(BaseModel):

    name = models.CharField("渠道商名称", max_length=128, null=True, blank=True)
    address = models.CharField("地址", max_length=256, null=True, blank=True)
    contact = models.CharField("联系人", max_length=128, null=True, blank=True)
    phone = models.CharField("电话", null=True, blank=True, max_length=128)
    email = models.EmailField("邮箱", null=True, blank=True)
    mpn_ids = models.IntegerField("MPN-ID", null=True, blank=True)
    org_ids = models.CharField("订阅ID", max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = "渠道商"
        verbose_name_plural = "渠道商"

    def __str__(self):
        return str(self.id)


class Consumer(BaseModel):
    """
    客户信息表
    注意： 客户不是系统内账户
    """
    com_name = models.CharField("公司名称", max_length=128, null=True, blank=True)
    email = models.EmailField("联系邮箱", null=True, blank=True)
    phone = models.IntegerField("联系电话", null=True, blank=True)
    channel = models.ForeignKey(
        Channel, verbose_name="代理商", on_delete=models.DO_NOTHING, db_constraint=False, null=True, blank=True
    )
    contact = models.CharField("联系人", max_length=128, null=True, blank=True)
    is_consumer = models.BooleanField("是否客户", null=True, blank=True)

    class Meta:
        verbose_name = "客户"
        verbose_name_plural = "客户"

    def __str__(self):
        return self.contact


ROLE_CHOICE = (
    (0, "管理员"),
    (1, "支持人员"),
    (2, "普通用户"),
)


class UserProfile(BaseModel):

    user = models.OneToOneField(
        User, verbose_name="用户名", on_delete=models.DO_NOTHING, db_constraint=False
    )
    cn_name = models.CharField("中文姓名", max_length=128, null=True, blank=True)
    job_title = models.CharField("岗位", max_length=128, null=True, blank=True)
    phone = models.IntegerField("电话", null=True, blank=True)
    email = models.EmailField("邮箱", null=True, blank=True)
    com_name = models.CharField("公司名称", max_length=128, null=True, blank=True)
    channel = models.ForeignKey(
        Channel, verbose_name="渠道", on_delete=models.DO_NOTHING, db_constraint=False, null=True, blank=True
    )
    role = models.IntegerField(
        "角色", null=True, blank=True, choices=ROLE_CHOICE, help_text="系统用来判断权限", default=2
    )

    class Meta:
        verbose_name = "用户配置文件"
        verbose_name_plural = "用户配置文件"

    def __str__(self):
        return self.user.username


ORDER_STATUS_CHOICE = (
    (0, "草稿"),
    (1, "已提交"),
    (2, "处理中"),
    (3, "驳回"),
    (4, "结束")
)

ORDER_CFY_CHOICE = (
    (1, "商务"),
    (2, "技术"),
)

PRIORITY_CHOICE = (
    (0, "普通"),
    (1, "中等"),
    (2, "高"),
    (3, "极高"),
)


class WorkOrder(BaseModel):

    channel = models.ForeignKey(Channel, verbose_name="渠道商", on_delete=models.DO_NOTHING, db_constraint=False)
    number = models.CharField("表单号", max_length=32, null=True, blank=True)
    title = models.CharField("工单标题", max_length=128)
    classify = models.IntegerField(
        "工单类型", null=True, blank=True, choices=ORDER_CFY_CHOICE
    )
    content = models.TextField("工单正文")
    priority = models.IntegerField("优先级", default=0, choices=PRIORITY_CHOICE)
    status = models.IntegerField("状态", choices=ORDER_STATUS_CHOICE, default=0)
    proposer = models.ForeignKey(
        User, verbose_name="申请人", null=True, blank=True, db_constraint=False, on_delete=models.DO_NOTHING
    )
    consumer = models.ForeignKey(
        Consumer, verbose_name="客户", null=True, blank=True, db_constraint=False, on_delete=models.DO_NOTHING
    )
    processor = models.ForeignKey(
        User, verbose_name="当前处理人", null=True, blank=True, db_constraint=False,
        on_delete=models.DO_NOTHING, related_name="processor"
    )
    take_time = models.DateTimeField("领取时间", null=True, blank=True)
    actual_contact = models.CharField("实际联系人", null=True, blank=True, max_length=256)

    class Meta:
        verbose_name = "工单"
        verbose_name_plural = "工单"

    def __str__(self):
        return self.title


def order_file_upload_to(instance, filename):
    content = instance.file.file.read()
    content_hash = sha1(content).hexdigest()
    suffix = filename.split('.')[-1]
    args = [
            'order_files',
            '%s.%s' % (content_hash, suffix),
            ]
    return '/'.join(args)


class OrderAttachFile(BaseModel):

    title = models.CharField(max_length=32, blank=True, verbose_name="文件名")
    file = models.FileField(upload_to=order_file_upload_to, blank=True, verbose_name="文件")
    file_url = models.URLField(max_length=512, null=True, blank=True, verbose_name="文件url")
    order = models.ForeignKey(
        WorkOrder, verbose_name="工单", on_delete=models.DO_NOTHING, db_constraint=False, related_name="att_file"
    )

    class Meta:
        verbose_name = "工单附件"
        verbose_name_plural = "工单附件"

    def __str__(self):
        return self.title


ORDER_POOL_STATUS = (
    (0, "待领取"),
    (1, "已领取"),
)


class WorkOrderPool(BaseModel):

    order = models.OneToOneField(WorkOrder, on_delete=models.DO_NOTHING, db_constraint=False)
    status = models.BooleanField("领取状态", default=0, choices=ORDER_POOL_STATUS)

    class Meta:
        verbose_name = "工单池"
        verbose_name_plural = "工单池"

    def __str__(self):
        return self.order.title


class WorkOrderLog(BaseModel):

    user = models.ForeignKey(User, verbose_name="操作人", on_delete=models.DO_NOTHING, db_constraint=False)
    action = models.CharField("操作", max_length=128, null=True, blank=True)
    field = models.CharField("字段", max_length=128, null=True, blank=True)
    order = models.ForeignKey(
        WorkOrder, verbose_name="工单", on_delete=models.DO_NOTHING, db_constraint=False, null=True, blank=True
    )
    content = models.TextField("内容", null=True, blank=True)

    class Meta:
        verbose_name = "工单日志"
        verbose_name_plural = "工单日志"

    def __str__(self):
        return self.order.title


class UserAlert(BaseModel):
    pass


class ApplyVerifyCode(BaseModel):

    user = models.ForeignKey(User, verbose_name="申请人", on_delete=models.DO_NOTHING, db_constraint=False)
    code = models.IntegerField("验证码", help_text="4位随机数字")
    status = models.BooleanField("是否有效", default=1)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.code:
            self.code = random.randint(1024, 9999)
        super(self.__class__, self).save()


class SystemConf(BaseModel):

    admin_mail = models.TextField("审核邮箱", null=True, blank=True, help_text="此处邮箱接收审核邮件")
    service_mail = models.EmailField(
        "客服邮箱", null=True, blank=True, help_text="此邮箱显示在注册失败时"
    )
    public_mail = models.TextField("公共邮箱", null=True, blank=True, help_text="此处邮箱接收新工单提醒")

    class Meta:
        verbose_name = "系统设置"
        verbose_name_plural = "系统设置"

    def __str__(self):
        return "配置详情"


# class SMTPConf(BaseModel):
#
#     smtp_host = models.CharField("EMAIL_HOST", null=True, blank=True, max_length=128)
#     smtp_port = models.IntegerField("EMAIL_PORT", null=True, blank=True, default=25)
#     smtp_user = models.CharField("EMAIL_HOST_USER", null=True, blank=True, max_length=128)
#     smtp_pass = models.CharField("EMAIL_HOST_PASSWORD", null=True, blank=True, max_length=128)
#     smtp_prefix = models.CharField("EMAIL_SUBJECT_PREFIX", null=True, blank=True, max_length=128)
#     smtp_tls = models.BooleanField("EMAIL_USE_TLS", null=True, blank=True, default=True)
#
#     class Meta:
#         verbose_name = "SMTP配置"
#         verbose_name_plural = "SMTP配置"
#
#     def __str__(self):
#         return "SMTP配置"

apps/order/forms.py
from django import forms


class ImportChannelForm(forms.Form):
    """
    导入渠道的form，废弃
    """
    file = forms.FileField(required=False)


class RegisterForm(forms.Form):
    """
    用户注册Form验证
    """
    mpn_ids = forms.CharField(required=True)
    username = forms.CharField(required=True)
    email = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    password = forms.PasswordInput()
    retype = forms.PasswordInput()


class OrderCreatForm(forms.Form):
    """
    订单创建Form验证
    """
    title = forms.CharField()
    classify = forms.CharField()
    content = forms.Textarea()
    priority = forms.CharField(required=False)
    file = forms.FileField(
        error_messages={"required": "请添加附件"}, required=False
    )
    com_name = forms.CharField(
        error_messages={"required": "请填写公司名称"}
    )
    contact = forms.CharField(
        error_messages={"required": "请填写联系人"}
    )
    email = forms.EmailField(
        error_messages={"required": "请填写邮箱"}
    )
    phone = forms.IntegerField(
        error_messages={"required": "请填写电话"}
    )
    is_consumer = forms.BooleanField()

apps/order/templates/channel_detail.html
{% extends 'starter.html' %}
{% block Content %}
<div class="row">
  <div class="col-md-6">

    <!-- Profile Image -->
    <div class="box box-primary">
      <div class="box-body box-profile">
        <p class="text-muted text-center">{{ user.userprofile.title }}</p>
        <form action="/order/channel/{{ channel.id }}/update/" method="POST">{% csrf_token %}
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>渠道商名称</b>
            <a class="pull-right">
              <label>{{ channel.name }}</label>
            </a>
          </li>
          <li class="list-group-item">
            <b>地址</b>
            <a class="pull-right">
              <label>{{ channel.address }}</label>
            </a>
          </li>
          <li class="list-group-item">
            <b>联系人</b>
            <a class="pull-right">
                <label>{{ channel.contact }}</label>
            </a>
          </li>
          <li class="list-group-item">
            <b>电话</b>
            <a class="pull-right">
                <label>{{ channel.phone }}</label>
            </a>
          </li>
          <li class="list-group-item">
            <b>邮箱</b>
            <a class="pull-right">
              <label>{{ channel.email }}</label>
            </a>
          </li>
          <li class="list-group-item">
            <b>MPN-ID</b>
            <a class="pull-right">
              <input name="mpn_ids" disabled="disabled" value={{ channel.mpn_ids }}>
            </a>
          </li>
          <li class="list-group-item">
            <b>订阅ID</b>
            <a class="pull-right">
              <input name="org_ids" value={{ channel.org_ids }}>
            </a>
          </li>
        </ul>

        <button type="submit" class="btn btn-primary btn-block"><b>保存修改</b></button>
        </form>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->

    <!-- About Me Box -->
{#    <div class="box box-primary">#}
{#      <div class="box-header with-border">#}
{#        <h3 class="box-title">About Me</h3>#}
{#      </div>#}
{#      <!-- /.box-header -->#}
{#      <div class="box-body">#}
{#        <strong><i class="fa fa-book margin-r-5"></i> Education</strong>#}
{##}
{#        <p class="text-muted">#}
{#          B.S. in Computer Science from the University of Tennessee at Knoxville#}
{#        </p>#}
{##}
{#        <hr>#}
{##}
{#        <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>#}
{##}
{#        <p class="text-muted">Malibu, California</p>#}
{##}
{#        <hr>#}
{##}
{#        <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>#}
{##}
{#        <p>#}
{#          <span class="label label-danger">UI Design</span>#}
{#          <span class="label label-success">Coding</span>#}
{#          <span class="label label-info">Javascript</span>#}
{#          <span class="label label-warning">PHP</span>#}
{#          <span class="label label-primary">Node.js</span>#}
{#        </p>#}
{##}
{#        <hr>#}
{##}
{#        <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>#}
{##}
{#        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>#}
{#      </div>#}
{#      <!-- /.box-body -->#}
{#    </div>#}
    <!-- /.box -->
  </div>
</div>
{% endblock %}
{% block Script %}
  <script src="/static/dist/js/demo.js"></script>
  <script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
{% endblock %}

apps/order/templates/demo1.html
{% extends 'starter.html' %}
{% block Content %}

    Content is here !!!!!
{% endblock %}

apps/order/templates/order_detail.html
{% extends 'starter.html' %}
{% block Styles %}
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">
{% endblock %}
{% block Content %}
{% include "./modal/end_order.html" %}
{% include "./modal/pass_order.html" %}
{% include "./modal/reject_order.html" %}
<div class="row">
  <div class="col-md-9">
    <!-- Box Comment -->
    <div class="box box-widget">
      <div class="box-header with-border">
        <div class="user-block">
{#          <img class="img-circle" src="/static/dist/img/user1-128x128.jpg" alt="User Image">#}
          <span class="username"><label>{{ work_order.consumer.contact }}</label></span>
          <span class="description">{{ user.userprofile.channel.name }} - {{ work_order.consumer.com_name }}
            {{ work_order.dt_created }} </span>
          <span class="description">{{ work_order.number }} - {{ work_order.title }} -
            {{ work_order.get_classify_display }} - {{ work_order.consumer.phone }}</span>
          <span><strong>实际联系人</strong>： {{ work_order.actual_contact }}</span>
        </div>
        <!-- /.user-block -->
        <div class="box-tools">
          <button type="button" class="btn btn-box-tool" data-toggle="tooltip" title="">
            状态： <i class="fa fa-circle-o"></i>  &nbsp{{ work_order.get_status_display }}</button>
{#          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>#}
{#          </button>#}
{#          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>#}
        </div>
        <!-- /.box-tools -->
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <div>
          {% autoescape off %}
            {{ work_order.content }}
          {% endautoescape %}
        </div>

        <p>________________________________________________________</p>
        <p>
          <label class="label label-default">
            当前处理人：{{ work_order.processor.userprofile.cn_name }}--{{ work_order.processor.userprofile.phone }}
          </label>&nbsp
          <label>
            领取时间：{{ work_order.take_time }}
          </label>
        </p>
        {% for i in att_files %}
          <a href="/media/{{ i.file }}"><i class="fa fa-share"></i> {{ i.title }}</a>
        {% endfor %}
{#        <button type="button" class="btn btn-default btn-xs"><i class="fa fa-thumbs-o-up"></i> Like</button>#}
{#        <span class="pull-right text-muted">127 likes - 3 comments</span>#}
      </div>
      <!-- /.box-body -->
      <div class="box-footer box-comments">
        {% for log in process_logs %}
        <div class="box-comment">
          <!-- User image -->
{#          <img class="img-circle img-sm" src="/static/dist/img/user3-128x128.jpg" alt="User Image">#}

          <div class="comment-text">
                <span class="username">
                  {{ log.user.username }}
                  <span class="text-muted pull-right">{{ log.dt_created }}</span>
                </span><!-- /.username -->
            {{ log.content }}
          </div>
          <!-- /.comment-text -->
          {% endfor %}
        </div>
        <!-- /.box-comment -->
{#        <div class="box-comment">#}
{#          <!-- User image -->#}
{#          <img class="img-circle img-sm" src="/static/dist/img/user4-128x128.jpg" alt="User Image">#}
{##}
{#          <div class="comment-text">#}
{#                <span class="username">#}
{#                  Luna Stark#}
{#                  <span class="text-muted pull-right">8:03 PM Today</span>#}
{#                </span><!-- /.username -->#}
{#            It is a long established fact that a reader will be distracted#}
{#            by the readable content of a page when looking at its layout.#}
{#          </div>#}
{#          <!-- /.comment-text -->#}
{#        </div>#}
        <!-- /.box-comment -->
      </div>
      <!-- /.box-footer -->
      <div class="box-footer">
        <form action="/order/order/{{ work_order.pk }}/update/" method="POST">{% csrf_token %}
{#          <img class="img-responsive img-circle img-sm" src="/static/dist/img/user4-128x128.jpg" alt="Alt Text">#}
          <!-- .img-push is used to add margin to elements next to floating images -->
          <div class="img-push">
            <tr><input type="text" class="form-control input-sm"
                       name="reply" placeholder="Press enter to post comment"><br>
            <button type="submit" class="btn btn-primary pull-right">提交答复</button>
          </div>
        </form>
        {% if page_info.user.userprofile.role == 1 and work_order.status == 2 %}
        <div class="row">
          <div class="col-md-6">
          <button type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#end-order">结束工单</button>&nbsp
          <button type="button" class="btn btn-sm" data-toggle="modal" data-target="#pass-order">转交工单</button>
          <button type="button" class="btn btn-sm" data-toggle="modal" data-target="#reject-order">驳回工单</button>
          </div>
        </div>
        {% endif %}
      </div>
      <!-- /.box-footer -->
    </div>
    <!-- /.box -->
  </div>
  <!-- /.col -->
</div>
{% endblock %}
{% block Script %}
  <!-- Slimscroll -->
  <script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/dist/js/demo.js"></script>
{% endblock %}

apps/order/templates/order_pool_tables.html
{% extends 'starter.html' %}
{% block Styles %}

{% endblock %}
{% block Content %}
  <!-- /.row -->
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">{{ page_info.table_title }}</h3>
          <a href="/order/create/"></a>
          {% include 'modal/modal_take_order_from_poll.html' %}
          <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" id="table_search" class="form-control pull-right"
                     placeholder="Search">
              <div class="input-group-btn">
                <button type="submit" id="search" class="btn btn-default"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>ID</th>
              <th>表单号</th>
              <th>标题</th>
              <th>申请人</th>
              <th>状态</th>
              <th>提交时间</th>
              <th></th>
            </tr>
            {% for i in contacts %}
            <tr>
              <td>{{ i.id }}</td>
              <td><a href="/order/order/{{ i.order.id }}">{{ i.order.number }}</a></td>
              <td>{{ i.order.title }}</td>
              {% if i.order.proposer.userprofile.cn_name %}
                <td><a href="/profile/{{ i.order.proposer.id }}">{{ i.order.proposer.userprofile.cn_name }}</a></td>
              {% else %}
                <td><a href="/profile/{{ i.order.proposer.id }}">{{ i.order.proposer.username }}</a></td>
              {% endif %}
              <td><span class="label label-success">{{ i.get_status_display }}</span></td>
              <td>{{ i.dt_created }}</td>
              <td>
{#                <button type="button" class="btn btn-sm" data-toggle="modal"#}
{#                        data-target="#modal-take-order-from-poll" onclick="TransForm({{ i.id }})">#}
{#                      领取工单#}
{#                </button>#}
                <a href="/order/order_pool/{{ i.id }}/take/">点击领取</a>
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <ul class="pagination pagination-sm no-margin pull-right">
            {% if contacts.has_previous %}
            <li><a href="?page={{ contacts.previous_page_number }}">&laquo;</a></li>
            {% endif %}
            {% if page < 1 %}
              <li><a href="?page=1">1</a></li>
            {% elif page > paginator.num_pages %}
              <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% else %}
              <li><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
            <span class="current">
              Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
            </span>
            {% if contacts.has_next %}
            <li><a href="?page={{ contacts.next_page_number }}">&raquo;</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
      <!-- /.box -->
    </div>
  </div>
{% endblock %}
{% block Script %}
  <!-- Slimscroll -->
  <script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/dist/js/demo.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#search").click(function(){
        let q = $("#table_search").val();
        let url_arr = document.URL.split('?');

        // 判断当前是否存在参数
        if (url_arr[1]){
            window.location.href=document.URL + "&q=" + q;
        } else {
            window.location.href=url_arr[0] = "?q=" +q;
        }
      });
    });
  </script>
{% endblock %}

apps/order/templates/order_tables.html
{% extends 'starter.html' %}
{% block Styles %}

{% endblock %}
{% block Content %}
  <!-- /.row -->
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">{{ page_info.table_title }}</h3>
          {% if user.userprofile.role == 2 %}
            <a href="/order/create/">提交工单</a>
          {% endif %}
{#          {% include 'modal/modal_import_channel.html' %}#}
          <div class="box-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" id="table_search" class="form-control pull-right"
                     placeholder="Search">
              <div class="input-group-btn">
                <button type="submit" id="search" class="btn btn-default"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>ID</th>
              <th>表单号</th>
              <th>标题</th>
              <th>申请人</th>
              <th>渠道商</th>
              <th>工单类型</th>
              <th>状态</th>
              <th>提交时间</th>
            </tr>
            {% for i in contacts %}
            <tr>
              <td>{{ i.id }}</td>
              <td><a href="/order/order/{{ i.id }}">{{ i.number }}</a></td>
              <td>{{ i.title }}</td>
              {% if i.proposer.userprofile.cn_name %}
                <td><a href="/profile/{{ i.proposer.userprofile.id }}">{{ i.proposer.userprofile.cn_name }}</a></td>
              {% else %}
                <td><a href="/profile/{{ i.proposer.userprofile.id }}">{{ i.proposer.username }}</a></td>
              {% endif %}
              <td>{{ i.channel.name }}</td>
              <td>{{ i.get_classify_display }}</td>
              <td><span class="label label-success">{{ i.get_status_display }}</span></td>
              <td>{{ i.dt_created }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <ul class="pagination pagination-sm no-margin pull-right">
            {% if contacts.has_previous %}
            <li><a href="?page={{ contacts.previous_page_number }}">&laquo;</a></li>
            {% endif %}
            {% if page < 1 %}
              <li><a href="?page=1">1</a></li>
            {% elif page > paginator.num_pages %}
              <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% else %}
              <li><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
            <span class="current">
              Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
            </span>
            {% if contacts.has_next %}
            <li><a href="?page={{ contacts.next_page_number }}">&raquo;</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
      <!-- /.box -->
    </div>
  </div>
{% endblock %}
{% block Script %}
  <!-- Slimscroll -->
  <script src="/static/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="/static/bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/dist/js/demo.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#search").click(function(){
        let q = $("#table_search").val();
        let url_arr = document.URL.split('?');

        // 判断当前是否存在参数
        if (url_arr[1]){
            window.location.href=document.URL + "&q=" + q;
        } else {
            window.location.href=url_arr[0] = "?q=" +q;
        }
      });
    });
  </script>
{% endblock %}